import { JSX } from "react";
import "flag-icons/css/flag-icons.min.css";

export const countryList = [
  { name: "Afghanistan", code: "AF", phoneCode: "+93" },
  { name: "Aland Islands", code: "AX", phoneCode: "+358" },
  { name: "Albania", code: "AL", phoneCode: "+355" },
  { name: "Algeria", code: "DZ", phoneCode: "+213" },
  { name: "American Samoa", code: "AS", phoneCode: "+1684" },
  { name: "Andorra", code: "AD", phoneCode: "+376" },
  { name: "Angola", code: "AO", phoneCode: "+244" },
  { name: "Anguilla", code: "AI", phoneCode: "+1264" },
  { name: "Antarctica", code: "AQ", phoneCode: "+672" },
  { name: "Antigua and Barbuda", code: "AG", phoneCode: "+1268" },
  { name: "Argentina", code: "AR", phoneCode: "+54" },
  { name: "Armenia", code: "AM", phoneCode: "+374" },
  { name: "Aruba", code: "AW", phoneCode: "+297" },
  { name: "Australia", code: "AU", phoneCode: "+61" },
  { name: "Austria", code: "AT", phoneCode: "+43" },
  { name: "Azerbaijan", code: "AZ", phoneCode: "+994" },
  { name: "Bahamas", code: "BS", phoneCode: "+1242" },
  { name: "Bahrain", code: "BH", phoneCode: "+973" },
  { name: "Bangladesh", code: "BD", phoneCode: "+880" },
  { name: "Barbados", code: "BB", phoneCode: "+1246" },
  { name: "Belarus", code: "BY", phoneCode: "+375" },
  { name: "Belgium", code: "BE", phoneCode: "+32" },
  { name: "Belize", code: "BZ", phoneCode: "+501" },
  { name: "Benin", code: "BJ", phoneCode: "+229" },
  { name: "Bermuda", code: "BM", phoneCode: "+1441" },
  { name: "Bhutan", code: "BT", phoneCode: "+975" },
  { name: "Bolivia", code: "BO", phoneCode: "+591" },
  { name: "Bosnia and Herzegovina", code: "BA", phoneCode: "+387" },
  { name: "Botswana", code: "BW", phoneCode: "+267" },
  { name: "Brazil", code: "BR", phoneCode: "+55" },
  { name: "British Indian Ocean Territory", code: "IO", phoneCode: "+246" },
  { name: "Brunei Darussalam", code: "BN", phoneCode: "+673" },
  { name: "Bulgaria", code: "BG", phoneCode: "+359" },
  { name: "Burkina Faso", code: "BF", phoneCode: "+226" },
  { name: "Burundi", code: "BI", phoneCode: "+257" },
  { name: "Cambodia", code: "KH", phoneCode: "+855" },
  { name: "Cameroon", code: "CM", phoneCode: "+237" },
  { name: "Canada", code: "CA", phoneCode: "+1" },
  { name: "Cape Verde", code: "CV", phoneCode: "+238" },
  { name: "Cayman Islands", code: "KY", phoneCode: "+345" },
  { name: "Central African Republic", code: "CF", phoneCode: "+236" },
  { name: "Chad", code: "TD", phoneCode: "+235" },
  { name: "Chile", code: "CL", phoneCode: "+56" },
  { name: "China", code: "CN", phoneCode: "+86" },
  { name: "Colombia", code: "CO", phoneCode: "+57" },
  { name: "Comoros", code: "KM", phoneCode: "+269" },
  { name: "Congo", code: "CG", phoneCode: "+242" },
  { name: "Costa Rica", code: "CR", phoneCode: "+506" },
  { name: "Croatia", code: "HR", phoneCode: "+385" },
  { name: "Cuba", code: "CU", phoneCode: "+53" },
  { name: "Cyprus", code: "CY", phoneCode: "+357" },
  { name: "Czech Republic", code: "CZ", phoneCode: "+420" },
  { name: "Denmark", code: "DK", phoneCode: "+45" },
  { name: "Djibouti", code: "DJ", phoneCode: "+253" },
  { name: "Dominica", code: "DM", phoneCode: "+1767" },
  { name: "Dominican Republic", code: "DO", phoneCode: "+1809" },
  { name: "Ecuador", code: "EC", phoneCode: "+593" },
  { name: "Egypt", code: "EG", phoneCode: "+20" },
  { name: "El Salvador", code: "SV", phoneCode: "+503" },
  { name: "Equatorial Guinea", code: "GQ", phoneCode: "+240" },
  { name: "Eritrea", code: "ER", phoneCode: "+291" },
  { name: "Estonia", code: "EE", phoneCode: "+372" },
  { name: "Ethiopia", code: "ET", phoneCode: "+251" },
  { name: "Fiji", code: "FJ", phoneCode: "+679" },
  { name: "Finland", code: "FI", phoneCode: "+358" },
  { name: "France", code: "FR", phoneCode: "+33" },
  { name: "Germany", code: "DE", phoneCode: "+49" },
  { name: "Greece", code: "GR", phoneCode: "+30" },
  { name: "Greenland", code: "GL", phoneCode: "+299" },
  { name: "Guatemala", code: "GT", phoneCode: "+502" },
  { name: "Honduras", code: "HN", phoneCode: "+504" },
  { name: "Hungary", code: "HU", phoneCode: "+36" },
  { name: "Iceland", code: "IS", phoneCode: "+354" },
  { name: "India", code: "IN", phoneCode: "+91" },
  { name: "Indonesia", code: "ID", phoneCode: "+62" },
  { name: "Iran", code: "IR", phoneCode: "+98" },
  { name: "Iraq", code: "IQ", phoneCode: "+964" },
  { name: "Ireland", code: "IE", phoneCode: "+353" },
  { name: "Israel", code: "IL", phoneCode: "+972" },
  { name: "Italy", code: "IT", phoneCode: "+39" },
  { name: "Japan", code: "JP", phoneCode: "+81" },
  { name: "Jordan", code: "JO", phoneCode: "+962" },
  { name: "Kazakhstan", code: "KZ", phoneCode: "+77" },
  { name: "Kenya", code: "KE", phoneCode: "+254" },
  { name: "South Korea", code: "KR", phoneCode: "+82" },
  { name: "Kuwait", code: "KW", phoneCode: "+965" },
  { name: "Latvia", code: "LV", phoneCode: "+371" },
  { name: "Lebanon", code: "LB", phoneCode: "+961" },
  { name: "Lithuania", code: "LT", phoneCode: "+370" },
  { name: "Luxembourg", code: "LU", phoneCode: "+352" },
  { name: "Malaysia", code: "MY", phoneCode: "+60" },
  { name: "Maldives", code: "MV", phoneCode: "+960" },
  { name: "Malta", code: "MT", phoneCode: "+356" },
  { name: "Mexico", code: "MX", phoneCode: "+52" },
  { name: "Moldova", code: "MD", phoneCode: "+373" },
  { name: "Monaco", code: "MC", phoneCode: "+377" },
  { name: "Mongolia", code: "MN", phoneCode: "+976" },
  { name: "Montenegro", code: "ME", phoneCode: "+382" },
  { name: "Morocco", code: "MA", phoneCode: "+212" },
  { name: "Mozambique", code: "MZ", phoneCode: "+258" },
  { name: "Myanmar", code: "MM", phoneCode: "+95" },
  { name: "Namibia", code: "NA", phoneCode: "+264" },
  { name: "Nepal", code: "NP", phoneCode: "+977" },
  { name: "Netherlands", code: "NL", phoneCode: "+31" },
  { name: "New Zealand", code: "NZ", phoneCode: "+64" },
  { name: "Nigeria", code: "NG", phoneCode: "+234" },
  { name: "Norway", code: "NO", phoneCode: "+47" },
  { name: "Pakistan", code: "PK", phoneCode: "+92" },
  { name: "Panama", code: "PA", phoneCode: "+507" },
  { name: "Papua New Guinea", code: "PG", phoneCode: "+675" },
  { name: "Paraguay", code: "PY", phoneCode: "+595" },
  { name: "Peru", code: "PE", phoneCode: "+51" },
  { name: "Philippines", code: "PH", phoneCode: "+63" },
  { name: "Poland", code: "PL", phoneCode: "+48" },
  { name: "Portugal", code: "PT", phoneCode: "+351" },
  { name: "Qatar", code: "QA", phoneCode: "+974" },
  { name: "Romania", code: "RO", phoneCode: "+40" },
  { name: "Russia", code: "RU", phoneCode: "+7" },
  { name: "Saudi Arabia", code: "SA", phoneCode: "+966" },
  { name: "Serbia", code: "RS", phoneCode: "+381" },
  { name: "Singapore", code: "SG", phoneCode: "+65" },
  { name: "Slovakia", code: "SK", phoneCode: "+421" },
  { name: "Slovenia", code: "SI", phoneCode: "+386" },
  { name: "South Africa", code: "ZA", phoneCode: "+27" },
  { name: "South Sudan", code: "SS", phoneCode: "+211" },
  { name: "Spain", code: "ES", phoneCode: "+34" },
  { name: "Sri Lanka", code: "LK", phoneCode: "+94" },
  { name: "Sweden", code: "SE", phoneCode: "+46" },
  { name: "Switzerland", code: "CH", phoneCode: "+41" },
  { name: "Taiwan", code: "TW", phoneCode: "+886" },
  { name: "Thailand", code: "TH", phoneCode: "+66" },
  { name: "Turkey", code: "TR", phoneCode: "+90" },
  { name: "Ukraine", code: "UA", phoneCode: "+380" },
  { name: "United Arab Emirates", code: "AE", phoneCode: "+971" },
  { name: "United Kingdom", code: "GB", phoneCode: "+44" },
  { name: "United States", code: "US", phoneCode: "+1" },
  { name: "Vietnam", code: "VN", phoneCode: "+84" },
  { name: "Zimbabwe", code: "ZW", phoneCode: "+263" },
];

export const getFlagIcon = (location: string): JSX.Element => {
  const cleanLocation = location.trim().toLowerCase();

  if (cleanLocation === "worldwide" || cleanLocation === "remote") {
    return <span className="text-lg">🌍</span>;
  }

  const country = countryList.find((country) =>
    cleanLocation.includes(country.name.toLowerCase())
  );

  if (country) {
    return <span className={`fi fi-${country.code.toLowerCase()}`} />;
  }

  return <span className="text-lg">🌍</span>;
};
